# Generated by Django 5.2.9 on 2025-12-02 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fullfilment_status', models.CharField(default='PLACED', max_length=20)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('organic', models.CharField(default='non-organic', max_length=40)),
                ('quantity_available', models.IntegerField()),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produced_date', models.DateField(blank=True, null=True)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery_option', models.CharField(default='not-available', max_length=100)),
                ('product_status', models.CharField(default='AVAILABLE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('profile_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(blank=True, max_length=50, null=True)),
                ('l_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('tole', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('about', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_url', models.CharField(max_length=255)),
                ('media_type', models.CharField(blank=True, max_length=10, null=True)),
                ('product', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='media', to='backend.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id_gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='backend.orderrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('p_rating_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='backend.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='product_ratings', to='backend.users')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='backend.users'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='backend.users'),
        ),
        migrations.CreateModel(
            name='FarmerRating',
            fields=[
                ('r_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumer', models.ForeignKey(db_column='Consumer_id', on_delete=django.db.models.deletion.PROTECT, related_name='given_farmer_ratings', to='backend.users')),
                ('farmer', models.ForeignKey(db_column='Farmer_id', on_delete=django.db.models.deletion.PROTECT, related_name='farmer_ratings', to='backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('v_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_front', models.CharField(blank=True, max_length=50, null=True)),
                ('id_back', models.CharField(blank=True, max_length=50, null=True)),
                ('selfie_with_id', models.CharField(blank=True, max_length=50, null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pin', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='OrdProdLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_at_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='backend.orderrequest')),
                ('product', models.ForeignKey(db_column='P_id', on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
