# Generated by Django 5.2.9 on 2025-12-17 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fullfilment_status', models.CharField(default='PLACED', max_length=20)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_url', models.CharField(max_length=255)),
                ('media_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField()),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('profile_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(blank=True, max_length=50, null=True)),
                ('l_name', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('tole', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('phone02', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('about', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('is_organic', models.BooleanField(default=False)),
                ('quantity_available', models.IntegerField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produced_date', models.DateField()),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery_option', models.CharField(default='not-available', max_length=100)),
                ('product_status', models.CharField(default='AVAILABLE', max_length=100)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.productmedia')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id_gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.orderrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('PRating_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
                ('consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.users')),
            ],
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.users'),
        ),
        migrations.CreateModel(
            name='FarmerRating',
            fields=[
                ('R_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Consumer', to='backend.users')),
                ('Farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Farmer', to='backend.users')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.usersprofile'),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('V_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('id_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_front', models.CharField(blank=True, max_length=50, null=True)),
                ('id_back', models.CharField(blank=True, max_length=50, null=True)),
                ('Selfie_with_id', models.CharField(blank=True, max_length=50, null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pin', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='OrdProdLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_at_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.orderrequest')),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
            ],
            options={
                'unique_together': {('order_id', 'P_id')},
            },
        ),
    ]
