# Generated by Django 5.2.9 on 2025-12-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
