# Generated by Django 5.2.9 on 2025-12-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_users_is_active_tokens_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_status',
            field=models.CharField(default='ACTIVATED', max_length=20),
        ),
    ]
