# Generated by Django 5.2.9 on 2025-12-19 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_users_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
                ('actvity_type', models.CharField(max_length=50, blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)), # optional details
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now))
            ],
        ),
        migrations.RemoveField(
            model_name='tokens',
            name='last_activity',
        ),
    ]
