# Generated by Django 5.2.9 on 2025-12-19 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_users_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.users')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='tokens',
            name='last_activity',
        ),
    ]
