# Generated by Django 5.2.9 on 2025-12-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_useractivity_remove_tokens_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='profile_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
