# Generated by Django 5.2.9 on 2025-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_usersprofile_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
