# Generated by Django 5.2.8 on 2025-12-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='token_status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='municipal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
