# Generated by Django 5.2.8 on 2025-12-23 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_tokens_token_status_usersprofile_municipal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='last_activity',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users'),
        ),
    ]
