# Generated by Django 5.2.8 on 2025-12-23 22:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_tokens_token_status_usersprofile_municipal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users'),
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_to', to='backend.users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='backend.users')),
            ],
            options={
                'unique_together': {('user', 'target_user')},
            },
        ),
    ]
