# Generated by Django 5.2.8 on 2025-12-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_useractivity_last_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='id',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
