# Generated by Django 6.0 on 2025-12-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_useractivity_id_useractivity_activity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerrating',
            old_name='Consumer_id',
            new_name='consumer_id',
        ),
        migrations.RenameField(
            model_name='farmerrating',
            old_name='Farmer_id',
            new_name='farmer_id',
        ),
        migrations.RenameField(
            model_name='farmerrating',
            old_name='R_id',
            new_name='r_id',
        ),
        migrations.RenameField(
            model_name='orderrequest',
            old_name='user_id',
            new_name='consumer_id',
        ),
        migrations.RenameField(
            model_name='ordprodlink',
            old_name='P_id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='P_id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='registered_date',
            new_name='registered_at',
        ),
        migrations.RenameField(
            model_name='productrating',
            old_name='P_id',
            new_name='p_id',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='fullfilment_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='media_id',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='order_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='p_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.users'),
        ),
        migrations.AlterUniqueTogether(
            name='ordprodlink',
            unique_together={('order_id', 'p_id')},
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('wallet_id', 'user_id')},
        ),
    ]
