# Generated by Django 6.0 on 2025-12-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_consumer_id_farmerrating_consumer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='order_date',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='ordprodlink',
            old_name='price_at_sale',
            new_name='cost_per_unit',
        ),
    ]
