# Generated by Django 6.0 on 2026-01-03 19:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_order_date_orderrequest_ordered_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='PRating_id',
            new_name='ProductRating_id',
        ),
        migrations.AlterUniqueTogether(
            name='connections',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='ORDER_OTP',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_option',
            field=models.CharField(default='Not-Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(default='Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='user_type',
            field=models.CharField(default='Consumer', max_length=50),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('FarmerRate_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField()),
                ('rated_by', models.CharField(default='Consumer', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Consumer', to='backend.users')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Farmer', to='backend.users')),
            ],
        ),
        migrations.DeleteModel(
            name='FarmerRating',
        ),
    ]
