# Generated by Django 6.0 on 2026-01-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_prating_id_productrating_productrating_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connections',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED', 'BLOCKED'])), name='valid_status_connection'),
        ),
        migrations.AddConstraint(
            model_name='orderrequest',
            constraint=models.CheckConstraint(condition=models.Q(('order_status__in', ['PENDING', 'ACCEPTED', 'REJECTED'])), name='valid_order_status'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_option__in', ['Not-Available', 'Available']), ('product_status__in', ['Available', 'Sold', 'Expired'])), name='valid_product_status_delivery_option'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['image', 'video'])), name='valid_media_type'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rated_by__in', ['Farmer', 'Consumer'])), name='valid_rated_by'),
        ),
        migrations.AddConstraint(
            model_name='tokens',
            constraint=models.CheckConstraint(condition=models.Q(('token_status__in', ['ACTIVE', 'INACTIVE', 'SUSPENDED'])), name='valid_token_status'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SUCCESSFUL', 'FAILED'])), name='valid_status_transaction'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(condition=models.Q(('profile_status__in', ['PENDING', 'ACTIVATED', 'SUSPENDED', 'DELETED'])), name='valid_profile_status'),
        ),
        migrations.AddConstraint(
            model_name='usersprofile',
            constraint=models.CheckConstraint(condition=models.Q(('user_type__in', ['Consumer', 'Farmer', 'VerifiedConsumer', 'VerifiedFarmer', 'Admin', 'SuperAdmin'])), name='valid_user_type'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'VERIFIED', 'REJECTED'])), name='valid_status'),
        ),
    ]
