# Generated by Django 6.0 on 2026-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_connections_valid_status_connection_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connections',
            constraint=models.UniqueConstraint(fields=('user', 'target_user'), name='unique_user_connection'),
        ),
    ]
