# Generated by Django 6.0 on 2026-01-05 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_connections_unique_user_connection'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='valid_status_transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NRP', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='initiated_by',
            field=models.CharField(default='CUSTOMER', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backend.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SUCCESSFUL', 'FAILED', 'REFUNDED'])), name='valid_status_transaction'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['WALLET', 'COD', 'KHALTI', 'ESewa'])), name='valid_payment_method'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('initiated_by__in', ['CUSTOMER', 'ADMIN'])), name='valid_initiated_by'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id_gateway',
        ),
    ]
