# Generated by Django 6.0 on 2026-01-05 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_transaction_valid_status_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='product',
            name='payment_method_accepted',
            field=models.JSONField(default='Wallet', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backend.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.users'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method_accepted__in', ['Wallet', 'COD', 'KHALTI', 'ESewa'])), name='valid_payment_method_accepted'),
        ),
    ]
