# Generated by Django 6.0 on 2026-01-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_transaction_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment_method_accepted',
            field=models.JSONField(default=[{'cod': False, 'esewa': False, 'khalti': False, 'wallet': True}], max_length=100),
        ),
    ]
