# Generated by Django 6.0 on 2026-01-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_product_payment_method_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='payment_method_accepted',
        ),
        migrations.CreateModel(
            name='PaymentMethodAccepts',
            fields=[
                ('pm_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.JSONField(default=[{'COD': False, 'ESewa': False, 'KHALTI': False, 'WALLET': True}], max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
        ),
    ]
