# Generated by Django 6.0 on 2026-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_product_payment_method_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='valid_payment_method_accepted',
        ),
        migrations.AlterField(
            model_name='paymentmethodaccepts',
            name='payment_method',
            field=models.JSONField(blank=True, default=list, max_length=50),
        ),
    ]
