# Generated by Django 6.0 on 2026-01-07 21:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_drop_problematic_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='ProductRating_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='FarmerRate_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verification',
            name='V_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='OTPs',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('otp_type', models.CharField(default='LOGIN', max_length=20)),
                ('otp_status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('otp_status__in', ['ACTIVE', 'USED', 'EXPIRED'])), name='valid_otp_status')],
            },
        ),
    ]
