# Generated by Django 6.0 on 2026-01-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_product_p_id_alter_productmedia_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
