# Generated by Django 6.0 on 2026-01-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_useractivity_activity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='user_id',
            new_name='user',
        ),
    ]
