# Generated by Django 6.0 on 2026-01-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_rename_user_id_useractivity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='user',
            new_name='user_id',
        ),
    ]
