# Generated by Django 6.0 on 2026-01-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_rename_user_useractivity_user_id'),
    ]

    operations = [
    ]
