# Generated by Django 6.0 on 2026-01-08 16:02

from django.db import migrations, models
import django.utils.timezone




class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_rename_user_useractivity_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('otp_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('otp_type', models.CharField(default='LOGIN', max_length=20)),
                ('otp_status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Users')),
            ],
        ),
    ]

