# Generated by Django 6.0 on 2026-01-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_otp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='OTP',
            constraint=models.CheckConstraint(condition=models.Q(('otp_status__in', ['ACTIVE', 'USED', 'EXPIRED'])),
                        name='valid_otp_status'),
        ),
    ]
