# Generated by Django 6.0 on 2026-01-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_connection_valid_otp_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='otps',
            name='valid_otp_status',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='otp_id',
            new_name='id',
        ),
        migrations.DeleteModel(
            name='OTPs',
        ),
    ]
