# Generated by Django 6.0 on 2026-01-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_remove_otps_valid_otp_status_rename_otp_id_otp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='FarmerRate_id',
            new_name='Rate_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='farmer_id',
            new_name='rated_to',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='consumer_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate_for',
            field=models.CharField(default='Consumer', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Consumer', to='backend.users'),
        ),
    ]
