# Generated by Django 6.0 on 2026-01-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_rename_farmerrate_id_rating_rate_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='Rate_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
