# Generated by Django 6.0 on 2026-01-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_remove_rating_rate_id_rating_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate_for',
            new_name='rated_for',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='date',
            new_name='rated_update',
        ),
    ]
