# Generated by Django 6.0 on 2026-01-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_rename_rate_for_rating_rated_for_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='valid_rated_by',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rated_by', to='backend.users'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rated_to', to='backend.users'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rated_for__in', ['Farmer', 'Consumer'])), name='valid_rated_for'),
        ),
    ]
