# Generated by Django 6.0 on 2026-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_remove_rating_valid_rated_by_alter_rating_rated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
