# Generated by Django 6.0 on 2026-01-18 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_usersprofile_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usersprofile'),
        ),
        migrations.CreateModel(
            name='TrackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_catagory', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'product_catagory'], name='backend_tra_user_id_b2163e_idx')],
            },
        ),
    ]
