# Generated by Django 5.2.8 on 2026-01-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_users_profile_id_trackuser'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='users',
            name='valid_profile_status',
        ),
        migrations.RemoveConstraint(
            model_name='verification',
            name='valid_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='failure_reason',
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(condition=models.Q(('profile_status__in', ['PENDING', 'ACTIVATED', 'SUSPENDED', 'DEACTIVATE'])), name='valid_profile_status'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'VERIFIED', 'REJECTED', 'UNVERIFIED'])), name='valid_status'),
        ),
    ]
