# Generated by Django 5.2.8 on 2026-01-31 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_remove_users_valid_profile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiator', to='backend.users'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_to', to='backend.users'),
        ),
    ]
