# Generated by Django 5.2.8 on 2026-01-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_transaction_initiated_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='valid_payment_method',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['WALLET', 'QR'])), name='valid_payment_method'),
        ),
    ]
