# Generated by Django 6.0 on 2026-01-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_remove_transaction_valid_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='payment_method',
            field=models.JSONField(blank=True, default=list, max_length=50),
        ),
        migrations.DeleteModel(
            name='PaymentMethodAccepts',
        ),
    ]
