# Generated by Django 5.2.8 on 2026-02-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_usersprofile_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('secondary_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['primary_name'], name='backend_far_primary_346ea1_idx'), models.Index(fields=['secondary_name'], name='backend_far_seconda_70e8e1_idx'), models.Index(fields=['primary_name', 'secondary_name'], name='backend_far_primary_36ecaf_idx')],
                'unique_together': {('primary_name', 'secondary_name')},
            },
        ),
    ]
