# Generated by Django 6.0 on 2026-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmedia',
            name='valid_media_type',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='media_url',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ProductMedia',
        ),
    ]
