# Generated by Django 6.0 on 2026-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_remove_productmedia_valid_media_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farmproducts',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='farmproducts',
            name='primary_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='farmproducts',
            name='secondary_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Nepali Name'),
        ),
        migrations.AddConstraint(
            model_name='farmproducts',
            constraint=models.UniqueConstraint(fields=('primary_name', 'secondary_name'), name='unique_product_pair'),
        ),
    ]
