# Generated by Django 6.0 on 2026-02-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_alter_farmproducts_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmproducts',
            name='category',
            field=models.CharField(blank=True, choices=[('animal-feed', 'Animal Feed'), ('beverage', 'Beverage'), ('dairy', 'Dairy'), ('dry-fruit-nut', 'Dry Fruit & Nut'), ('egg', 'Egg'), ('fiber', 'Fiber'), ('fish', 'Fish'), ('flour', 'Flour'), ('flower', 'Flower'), ('fruit', 'Fruit'), ('general', 'General'), ('grain', 'Grain'), ('legume', 'Legume'), ('livestock-poultry', 'Livestock & Poultry'), ('meat', 'Meat'), ('medicinal-herb', 'Medicinal Herb'), ('misc', 'Miscellaneous'), ('mushroom', 'Mushroom'), ('oil', 'Oil'), ('processed-food', 'Processed Food'), ('salt', 'Salt'), ('spice', 'Spice'), ('sweetener', 'Sweetener'), ('timber', 'Timber'), ('tobacco', 'Tobacco'), ('tool-equipment', 'Tool & Equipment'), ('vegetable', 'Vegetable')], db_index=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AddIndex(
            model_name='farmproducts',
            index=models.Index(fields=['category'], name='backend_far_categor_42ff4c_idx'),
        ),
    ]
