# Generated by Django 6.0 on 2026-02-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_farmproducts_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackuser',
            name='farmProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.farmproducts'),
        ),
        migrations.AlterField(
            model_name='trackuser',
            name='product_catagory',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='trackuser',
            index=models.Index(fields=['user_id', 'score'], name='backend_tra_user_id_2615cb_idx'),
        ),
        migrations.AddIndex(
            model_name='trackuser',
            index=models.Index(fields=['farmProduct', 'score'], name='backend_tra_farmPro_72ab4e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackuser',
            index=models.Index(fields=['product_catagory', 'score'], name='backend_tra_product_d8d718_idx'),
        ),
        migrations.AddIndex(
            model_name='trackuser',
            index=models.Index(fields=['user_id', 'farmProduct'], name='backend_tra_user_id_e4ab21_idx'),
        ),
        migrations.AddIndex(
            model_name='trackuser',
            index=models.Index(fields=['user_id', 'score', 'farmProduct'], name='backend_tra_user_id_d560a0_idx'),
        ),
        migrations.AddIndex(
            model_name='trackuser',
            index=models.Index(fields=['user_id', 'product_catagory', 'score'], name='backend_tra_user_id_20a549_idx'),
        ),
    ]
