# Generated by Django 6.0 on 2026-02-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_trackuser_farmproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
