# Generated by Django 6.0 on 2026-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_otp_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('FORGOT_PASSWORD', 'Forgot Password'), ('REGISTER', 'Register'), ('ORDER', 'Order'), ('VERIFICATION', 'Verification'), ('WALLET_WITHDRAWAL', 'Wallet Withdrawal'), ('BIG_FILE_TRANSFER', 'Big File Transfer')], default='LOGIN', max_length=20),
        ),
    ]
