# Generated by Django 6.0 on 2026-02-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_rename_discription_otp_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
