# Generated by Django 6.0 on 2026-02-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_alter_otp_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('FORGOT_PASSWORD', 'Forgot Password'), ('REGISTER', 'Register'), ('ORDER', 'Order'), ('VERIFICATION', 'Verification'), ('WALLET_WITHDRAWAL', 'Wallet Withdrawal')], default='LOGIN', max_length=20),
        ),
    ]
