# Generated by Django 6.0 on 2026-02-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_alter_otp_description_alter_otp_otp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
