# Generated by Django 6.0 on 2026-02-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_alter_product_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
