# Generated by Django 6.0 on 2026-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_alter_product_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
