# Generated by Django 6.0 on 2026-02-23 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_alter_productrating_score_alter_rating_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rated_update',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='productrating',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rating',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
