# Generated by Django 6.0 on 2026-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_rename_date_productrating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
