# Generated by Django 6.0 on 2026-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_alter_productrating_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verification',
            name='valid_status',
        ),
        migrations.AddField(
            model_name='verification',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'VERIFIED', 'REJECTED'])), name='valid_status'),
        ),
    ]
