# Generated by Django 6.0 on 2026-02-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_remove_verification_valid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
