# Generated by Django 6.0 on 2026-02-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_alter_usersprofile_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='users',
            name='valid_profile_status',
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(condition=models.Q(('profile_status__in', ['PENDING', 'ACTIVATED', 'SUSPENDED', 'DEACTIVATED'])), name='valid_profile_status'),
        ),
    ]
