# Generated by Django 6.0 on 2026-02-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_remove_users_valid_profile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
