# Generated by Django 6.0 on 2026-02-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_product_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.CharField(default='KG', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type__in', ['', 'None', 'Percentage', 'Fixed'])), name='valid_discount_type'),
        ),
    ]
