# Generated by Django 6.0 on 2026-02-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_product_product_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
