# Generated by Django 6.0 on 2026-02-26 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_alter_usersprofile_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackUser',
            new_name='ProductScore',
        ),
        migrations.AlterUniqueTogether(
            name='ordprodlink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ordprodlink',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='ordprodlink',
            name='p_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_type',
        ),
        migrations.RenameIndex(
            model_name='productscore',
            new_name='backend_pro_user_id_07dae5_idx',
            old_name='backend_tra_user_id_b2163e_idx',
        ),
        migrations.RenameIndex(
            model_name='productscore',
            new_name='backend_pro_user_id_2a54ac_idx',
            old_name='backend_tra_user_id_2615cb_idx',
        ),
        migrations.RenameIndex(
            model_name='productscore',
            new_name='backend_pro_farmPro_606134_idx',
            old_name='backend_tra_farmPro_72ab4e_idx',
        ),
        migrations.RenameIndex(
            model_name='productscore',
            new_name='backend_pro_product_450f7e_idx',
            old_name='backend_tra_product_d8d718_idx',
        ),
        migrations.RenameIndex(
            model_name='productscore',
            new_name='backend_pro_user_id_8fef4e_idx',
            old_name='backend_tra_user_id_e4ab21_idx',
        ),
        migrations.RenameIndex(
            model_name='productscore',
            new_name='backend_pro_user_id_8d137c_idx',
            old_name='backend_tra_user_id_d560a0_idx',
        ),
        migrations.RenameIndex(
            model_name='productscore',
            new_name='backend_pro_user_id_181aef_idx',
            old_name='backend_tra_user_id_20a549_idx',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.product'),
        ),
        migrations.DeleteModel(
            name='OrdProdLink',
        ),
    ]
