# Generated by Django 6.0 on 2026-02-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_rename_trackuser_productscore_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='valid_product_status_delivery_option',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_option__in', ['Not-Available', 'Available']), ('product_status__in', ['Available', 'Sold', 'Expired', 'Deleted'])), name='valid_product_status_delivery_option'),
        ),
    ]
