# Generated by Django 6.0 on 2026-02-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_remove_product_valid_product_status_delivery_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
