# Generated by Django 6.0 on 2026-02-27 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='latest_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
