# Generated by Django 6.0 on 2026-02-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_orderrequest_latest_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='product',
            new_name='p_id',
        ),
    ]
