# Generated by Django 6.0 on 2026-02-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_rename_product_orderrequest_p_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='p_id',
            new_name='product',
        ),
    ]
