# Generated by Django 6.0 on 2026-02-27 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_rename_p_id_orderrequest_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='product',
            field=models.ForeignKey(blank=True, db_column='p_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.product'),
        ),
    ]
