# Generated by Django 6.0 on 2026-03-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_remove_product_valid_discount_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='valid_discount_type',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type__in', ['', 'None', 'Percentage', 'Fixed'])), name='valid_discount_type'),
        ),
    ]
