# Generated by Django 6.0 on 2026-03-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_remove_product_valid_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='message',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='ordered_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
