# Generated by Django 6.0 on 2026-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_orderrequest_message_orderrequest_ordered_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='ORDER_OTP',
            field=models.CharField(blank=True, db_column='order_otp', max_length=6, null=True),
        ),
    ]
