# Generated by Django 6.0 on 2026-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_alter_orderrequest_order_otp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderrequest',
            name='valid_order_status',
        ),
        migrations.AddConstraint(
            model_name='orderrequest',
            constraint=models.CheckConstraint(condition=models.Q(('order_status__in', ['PENDING', 'ACCEPTED', 'REJECTED', 'DELIVERED'])), name='valid_order_status'),
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='ORDER_OTP',
        ),
    ]
