# Generated by Django 6.0 on 2026-03-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_remove_orderrequest_valid_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='ORDER_OTP',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
