# Generated by Django 6.0 on 2026-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_orderrequest_order_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='orderrequest',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['WALLET', 'CashOnDelivery'])), name='valid_payment_method_for_order'),
        ),
    ]
