# Generated by Django 6.0 on 2026-03-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_orderrequest_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='valid_initiated_by',
        ),
    ]
