# Generated by Django 6.0 on 2026-03-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_remove_transaction_valid_initiated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.orderrequest', unique=True),
        ),
    ]
