# Generated by Django 6.0 on 2026-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_alter_transaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='produced_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
