# Generated by Django 6.0 on 2026-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_alter_product_produced_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='valid_product_status_delivery_option',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_option__in', ['Not-Available', 'Available']), ('product_status__in', ['Available', 'Sold', 'Expired', 'Deleted', 'Not-Available', 'Disable', 'Discontinued'])), name='valid_product_status_delivery_option'),
        ),
    ]
