# Generated by Django 6.0 on 2026-03-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_remove_product_valid_product_status_delivery_option_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='valid_discount_type',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type__in', ['', 'None', 'Percentage', 'Fixed', 'Flat']), ('discount_type__isnull', True), _connector='OR'), name='valid_discount_type'),
        ),
    ]
