# Generated by Django 6.0 on 2026-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_remove_orderrequest_valid_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='valid_payment_method',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['WALLET', 'CASH'])), name='valid_payment_method'),
        ),
    ]
