# Generated by Django 6.0 on 2026-03-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_remove_transaction_valid_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderrequest',
            name='valid_order_status',
        ),
        migrations.AddConstraint(
            model_name='orderrequest',
            constraint=models.CheckConstraint(condition=models.Q(('order_status__in', ['PENDING', 'ACCEPTED', 'REJECTED', 'DELIVERED', 'PENDING_DELIVERY', 'CANCELLED'])), name='valid_order_status'),
        ),
    ]
